/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as PrincipalIndexRouteImport } from './routes/principal/index'
import { Route as PrincipalSubjectsRouteImport } from './routes/principal/subjects'
import { Route as PrincipalStudentsRouteImport } from './routes/principal/students'
import { Route as PrincipalResultsRouteImport } from './routes/principal/results'
import { Route as PrincipalMonitorRouteImport } from './routes/principal/monitor'
import { Route as PrincipalAuditRouteImport } from './routes/principal/audit'
import { Route as PrincipalQuestionsIndexRouteImport } from './routes/principal/questions.index'
import { Route as PrincipalExamsIndexRouteImport } from './routes/principal/exams.index'
import { Route as StudentReviewStudentExamIdRouteImport } from './routes/student/review.$studentExamId'
import { Route as StudentResultsStudentExamIdRouteImport } from './routes/student/results.$studentExamId'
import { Route as StudentExamExamIdRouteImport } from './routes/student/exam.$examId'
import { Route as PrincipalStudentsStudentIdRouteImport } from './routes/principal/students.$studentId'
import { Route as PrincipalQuestionsNewRouteImport } from './routes/principal/questions.new'
import { Route as PrincipalQuestionsImportRouteImport } from './routes/principal/questions.import'
import { Route as PrincipalExamsNewRouteImport } from './routes/principal/exams.new'
import { Route as StudentExamExamIdAttemptRouteImport } from './routes/student/exam.$examId.attempt'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalIndexRoute = PrincipalIndexRouteImport.update({
  id: '/principal/',
  path: '/principal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalSubjectsRoute = PrincipalSubjectsRouteImport.update({
  id: '/principal/subjects',
  path: '/principal/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalStudentsRoute = PrincipalStudentsRouteImport.update({
  id: '/principal/students',
  path: '/principal/students',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalResultsRoute = PrincipalResultsRouteImport.update({
  id: '/principal/results',
  path: '/principal/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalMonitorRoute = PrincipalMonitorRouteImport.update({
  id: '/principal/monitor',
  path: '/principal/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalAuditRoute = PrincipalAuditRouteImport.update({
  id: '/principal/audit',
  path: '/principal/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalQuestionsIndexRoute = PrincipalQuestionsIndexRouteImport.update({
  id: '/principal/questions/',
  path: '/principal/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalExamsIndexRoute = PrincipalExamsIndexRouteImport.update({
  id: '/principal/exams/',
  path: '/principal/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReviewStudentExamIdRoute =
  StudentReviewStudentExamIdRouteImport.update({
    id: '/student/review/$studentExamId',
    path: '/student/review/$studentExamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentResultsStudentExamIdRoute =
  StudentResultsStudentExamIdRouteImport.update({
    id: '/student/results/$studentExamId',
    path: '/student/results/$studentExamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentExamExamIdRoute = StudentExamExamIdRouteImport.update({
  id: '/student/exam/$examId',
  path: '/student/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalStudentsStudentIdRoute =
  PrincipalStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => PrincipalStudentsRoute,
  } as any)
const PrincipalQuestionsNewRoute = PrincipalQuestionsNewRouteImport.update({
  id: '/principal/questions/new',
  path: '/principal/questions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalQuestionsImportRoute =
  PrincipalQuestionsImportRouteImport.update({
    id: '/principal/questions/import',
    path: '/principal/questions/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrincipalExamsNewRoute = PrincipalExamsNewRouteImport.update({
  id: '/principal/exams/new',
  path: '/principal/exams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentExamExamIdAttemptRoute =
  StudentExamExamIdAttemptRouteImport.update({
    id: '/attempt',
    path: '/attempt',
    getParentRoute: () => StudentExamExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/principal/audit': typeof PrincipalAuditRoute
  '/principal/monitor': typeof PrincipalMonitorRoute
  '/principal/results': typeof PrincipalResultsRoute
  '/principal/students': typeof PrincipalStudentsRouteWithChildren
  '/principal/subjects': typeof PrincipalSubjectsRoute
  '/principal/': typeof PrincipalIndexRoute
  '/student/': typeof StudentIndexRoute
  '/principal/exams/new': typeof PrincipalExamsNewRoute
  '/principal/questions/import': typeof PrincipalQuestionsImportRoute
  '/principal/questions/new': typeof PrincipalQuestionsNewRoute
  '/principal/students/$studentId': typeof PrincipalStudentsStudentIdRoute
  '/student/exam/$examId': typeof StudentExamExamIdRouteWithChildren
  '/student/results/$studentExamId': typeof StudentResultsStudentExamIdRoute
  '/student/review/$studentExamId': typeof StudentReviewStudentExamIdRoute
  '/principal/exams/': typeof PrincipalExamsIndexRoute
  '/principal/questions/': typeof PrincipalQuestionsIndexRoute
  '/student/exam/$examId/attempt': typeof StudentExamExamIdAttemptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/principal/audit': typeof PrincipalAuditRoute
  '/principal/monitor': typeof PrincipalMonitorRoute
  '/principal/results': typeof PrincipalResultsRoute
  '/principal/students': typeof PrincipalStudentsRouteWithChildren
  '/principal/subjects': typeof PrincipalSubjectsRoute
  '/principal': typeof PrincipalIndexRoute
  '/student': typeof StudentIndexRoute
  '/principal/exams/new': typeof PrincipalExamsNewRoute
  '/principal/questions/import': typeof PrincipalQuestionsImportRoute
  '/principal/questions/new': typeof PrincipalQuestionsNewRoute
  '/principal/students/$studentId': typeof PrincipalStudentsStudentIdRoute
  '/student/exam/$examId': typeof StudentExamExamIdRouteWithChildren
  '/student/results/$studentExamId': typeof StudentResultsStudentExamIdRoute
  '/student/review/$studentExamId': typeof StudentReviewStudentExamIdRoute
  '/principal/exams': typeof PrincipalExamsIndexRoute
  '/principal/questions': typeof PrincipalQuestionsIndexRoute
  '/student/exam/$examId/attempt': typeof StudentExamExamIdAttemptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/principal/audit': typeof PrincipalAuditRoute
  '/principal/monitor': typeof PrincipalMonitorRoute
  '/principal/results': typeof PrincipalResultsRoute
  '/principal/students': typeof PrincipalStudentsRouteWithChildren
  '/principal/subjects': typeof PrincipalSubjectsRoute
  '/principal/': typeof PrincipalIndexRoute
  '/student/': typeof StudentIndexRoute
  '/principal/exams/new': typeof PrincipalExamsNewRoute
  '/principal/questions/import': typeof PrincipalQuestionsImportRoute
  '/principal/questions/new': typeof PrincipalQuestionsNewRoute
  '/principal/students/$studentId': typeof PrincipalStudentsStudentIdRoute
  '/student/exam/$examId': typeof StudentExamExamIdRouteWithChildren
  '/student/results/$studentExamId': typeof StudentResultsStudentExamIdRoute
  '/student/review/$studentExamId': typeof StudentReviewStudentExamIdRoute
  '/principal/exams/': typeof PrincipalExamsIndexRoute
  '/principal/questions/': typeof PrincipalQuestionsIndexRoute
  '/student/exam/$examId/attempt': typeof StudentExamExamIdAttemptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/principal/audit'
    | '/principal/monitor'
    | '/principal/results'
    | '/principal/students'
    | '/principal/subjects'
    | '/principal/'
    | '/student/'
    | '/principal/exams/new'
    | '/principal/questions/import'
    | '/principal/questions/new'
    | '/principal/students/$studentId'
    | '/student/exam/$examId'
    | '/student/results/$studentExamId'
    | '/student/review/$studentExamId'
    | '/principal/exams/'
    | '/principal/questions/'
    | '/student/exam/$examId/attempt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/principal/audit'
    | '/principal/monitor'
    | '/principal/results'
    | '/principal/students'
    | '/principal/subjects'
    | '/principal'
    | '/student'
    | '/principal/exams/new'
    | '/principal/questions/import'
    | '/principal/questions/new'
    | '/principal/students/$studentId'
    | '/student/exam/$examId'
    | '/student/results/$studentExamId'
    | '/student/review/$studentExamId'
    | '/principal/exams'
    | '/principal/questions'
    | '/student/exam/$examId/attempt'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/principal/audit'
    | '/principal/monitor'
    | '/principal/results'
    | '/principal/students'
    | '/principal/subjects'
    | '/principal/'
    | '/student/'
    | '/principal/exams/new'
    | '/principal/questions/import'
    | '/principal/questions/new'
    | '/principal/students/$studentId'
    | '/student/exam/$examId'
    | '/student/results/$studentExamId'
    | '/student/review/$studentExamId'
    | '/principal/exams/'
    | '/principal/questions/'
    | '/student/exam/$examId/attempt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  PrincipalAuditRoute: typeof PrincipalAuditRoute
  PrincipalMonitorRoute: typeof PrincipalMonitorRoute
  PrincipalResultsRoute: typeof PrincipalResultsRoute
  PrincipalStudentsRoute: typeof PrincipalStudentsRouteWithChildren
  PrincipalSubjectsRoute: typeof PrincipalSubjectsRoute
  PrincipalIndexRoute: typeof PrincipalIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  PrincipalExamsNewRoute: typeof PrincipalExamsNewRoute
  PrincipalQuestionsImportRoute: typeof PrincipalQuestionsImportRoute
  PrincipalQuestionsNewRoute: typeof PrincipalQuestionsNewRoute
  StudentExamExamIdRoute: typeof StudentExamExamIdRouteWithChildren
  StudentResultsStudentExamIdRoute: typeof StudentResultsStudentExamIdRoute
  StudentReviewStudentExamIdRoute: typeof StudentReviewStudentExamIdRoute
  PrincipalExamsIndexRoute: typeof PrincipalExamsIndexRoute
  PrincipalQuestionsIndexRoute: typeof PrincipalQuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/': {
      id: '/principal/'
      path: '/principal'
      fullPath: '/principal/'
      preLoaderRoute: typeof PrincipalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/subjects': {
      id: '/principal/subjects'
      path: '/principal/subjects'
      fullPath: '/principal/subjects'
      preLoaderRoute: typeof PrincipalSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/students': {
      id: '/principal/students'
      path: '/principal/students'
      fullPath: '/principal/students'
      preLoaderRoute: typeof PrincipalStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/results': {
      id: '/principal/results'
      path: '/principal/results'
      fullPath: '/principal/results'
      preLoaderRoute: typeof PrincipalResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/monitor': {
      id: '/principal/monitor'
      path: '/principal/monitor'
      fullPath: '/principal/monitor'
      preLoaderRoute: typeof PrincipalMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/audit': {
      id: '/principal/audit'
      path: '/principal/audit'
      fullPath: '/principal/audit'
      preLoaderRoute: typeof PrincipalAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/questions/': {
      id: '/principal/questions/'
      path: '/principal/questions'
      fullPath: '/principal/questions/'
      preLoaderRoute: typeof PrincipalQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/exams/': {
      id: '/principal/exams/'
      path: '/principal/exams'
      fullPath: '/principal/exams/'
      preLoaderRoute: typeof PrincipalExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/review/$studentExamId': {
      id: '/student/review/$studentExamId'
      path: '/student/review/$studentExamId'
      fullPath: '/student/review/$studentExamId'
      preLoaderRoute: typeof StudentReviewStudentExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results/$studentExamId': {
      id: '/student/results/$studentExamId'
      path: '/student/results/$studentExamId'
      fullPath: '/student/results/$studentExamId'
      preLoaderRoute: typeof StudentResultsStudentExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/exam/$examId': {
      id: '/student/exam/$examId'
      path: '/student/exam/$examId'
      fullPath: '/student/exam/$examId'
      preLoaderRoute: typeof StudentExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/students/$studentId': {
      id: '/principal/students/$studentId'
      path: '/$studentId'
      fullPath: '/principal/students/$studentId'
      preLoaderRoute: typeof PrincipalStudentsStudentIdRouteImport
      parentRoute: typeof PrincipalStudentsRoute
    }
    '/principal/questions/new': {
      id: '/principal/questions/new'
      path: '/principal/questions/new'
      fullPath: '/principal/questions/new'
      preLoaderRoute: typeof PrincipalQuestionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/questions/import': {
      id: '/principal/questions/import'
      path: '/principal/questions/import'
      fullPath: '/principal/questions/import'
      preLoaderRoute: typeof PrincipalQuestionsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/exams/new': {
      id: '/principal/exams/new'
      path: '/principal/exams/new'
      fullPath: '/principal/exams/new'
      preLoaderRoute: typeof PrincipalExamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/exam/$examId/attempt': {
      id: '/student/exam/$examId/attempt'
      path: '/attempt'
      fullPath: '/student/exam/$examId/attempt'
      preLoaderRoute: typeof StudentExamExamIdAttemptRouteImport
      parentRoute: typeof StudentExamExamIdRoute
    }
  }
}

interface PrincipalStudentsRouteChildren {
  PrincipalStudentsStudentIdRoute: typeof PrincipalStudentsStudentIdRoute
}

const PrincipalStudentsRouteChildren: PrincipalStudentsRouteChildren = {
  PrincipalStudentsStudentIdRoute: PrincipalStudentsStudentIdRoute,
}

const PrincipalStudentsRouteWithChildren =
  PrincipalStudentsRoute._addFileChildren(PrincipalStudentsRouteChildren)

interface StudentExamExamIdRouteChildren {
  StudentExamExamIdAttemptRoute: typeof StudentExamExamIdAttemptRoute
}

const StudentExamExamIdRouteChildren: StudentExamExamIdRouteChildren = {
  StudentExamExamIdAttemptRoute: StudentExamExamIdAttemptRoute,
}

const StudentExamExamIdRouteWithChildren =
  StudentExamExamIdRoute._addFileChildren(StudentExamExamIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  PrincipalAuditRoute: PrincipalAuditRoute,
  PrincipalMonitorRoute: PrincipalMonitorRoute,
  PrincipalResultsRoute: PrincipalResultsRoute,
  PrincipalStudentsRoute: PrincipalStudentsRouteWithChildren,
  PrincipalSubjectsRoute: PrincipalSubjectsRoute,
  PrincipalIndexRoute: PrincipalIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  PrincipalExamsNewRoute: PrincipalExamsNewRoute,
  PrincipalQuestionsImportRoute: PrincipalQuestionsImportRoute,
  PrincipalQuestionsNewRoute: PrincipalQuestionsNewRoute,
  StudentExamExamIdRoute: StudentExamExamIdRouteWithChildren,
  StudentResultsStudentExamIdRoute: StudentResultsStudentExamIdRoute,
  StudentReviewStudentExamIdRoute: StudentReviewStudentExamIdRoute,
  PrincipalExamsIndexRoute: PrincipalExamsIndexRoute,
  PrincipalQuestionsIndexRoute: PrincipalQuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
